-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 23:37:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `offerprocessing`.`AddressTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`AddressTypes` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`AddressTypes` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `AddressType` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`Addresss`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`Addresss` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`Addresss` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Line1` VARCHAR(100) NOT NULL,
  `Line2` VARCHAR(100) NULL DEFAULT NULL,
  `Line3` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(100) NOT NULL,
  `ZipPostalCode` VARCHAR(20) NOT NULL,
  `StateProvinceCounty` VARCHAR(50) NOT NULL,
  `Country` VARCHAR(50) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`BundleOfferStatusTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`BundleOfferStatusTypes` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`BundleOfferStatusTypes` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(20) NOT NULL,
  `Description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`BundleOfferMappings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`BundleOfferMappings` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`BundleOfferMappings` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConsumerOfferBundleId` BIGINT(20) NOT NULL,
  `SupplierOfferId` BIGINT(20) NOT NULL,
  `BundleOfferStatusTypeId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `BOMStatusTypeId_idx` (`BundleOfferStatusTypeId` ASC),
  CONSTRAINT `BOMStatusTypeId`
    FOREIGN KEY (`BundleOfferStatusTypeId`)
    REFERENCES `offerprocessing`.`BundleOfferStatusTypes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`Marketers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`Marketers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`Marketers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Domain` VARCHAR(100) NOT NULL,
  `MarketerType` VARCHAR(100) NULL DEFAULT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Currency` VARCHAR(3) NULL DEFAULT 'USD',
  `Description` VARCHAR(250) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`Consumers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`Consumers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`Consumers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MarketerId` BIGINT(20) NOT NULL,
  `Handle` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `FirstName` VARCHAR(100) NULL DEFAULT NULL,
  `MiddleName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(100) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT b'0',
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  PRIMARY KEY (`Id`),
  INDEX `MarketerKeyId_idx` (`MarketerId` ASC),
  CONSTRAINT `CMarketerKeyId`
    FOREIGN KEY (`MarketerId`)
    REFERENCES `offerprocessing`.`Marketers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`ConsumerAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`ConsumerAddress` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`ConsumerAddress` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConsumerId` BIGINT(20) NOT NULL,
  `AddressId` BIGINT(20) NOT NULL,
  `ConsumerAddressTypeId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_idx` (`ConsumerAddressTypeId` ASC),
  INDEX `CACKeyId_idx` (`ConsumerId` ASC),
  INDEX `CAAddressKeyId_idx` (`AddressId` ASC),
  CONSTRAINT `AddressTypeId`
    FOREIGN KEY (`ConsumerAddressTypeId`)
    REFERENCES `offerprocessing`.`AddressTypes` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CACKeyId`
    FOREIGN KEY (`ConsumerId`)
    REFERENCES `offerprocessing`.`Consumers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CAAddressKeyId`
    FOREIGN KEY (`AddressId`)
    REFERENCES `offerprocessing`.`Addresss` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`Products` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`Products` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Manufacturer` VARCHAR(100) NOT NULL,
  `EAN` VARCHAR(50) NULL DEFAULT NULL,
  `GTIN` VARCHAR(50) NULL DEFAULT NULL,
  `UOM` VARCHAR(50) NULL DEFAULT NULL,
  `Description` VARCHAR(250) NULL DEFAULT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`MarketerProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`MarketerProducts` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`MarketerProducts` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MarketerId` BIGINT(20) NOT NULL,
  `ProductId` BIGINT(20) NOT NULL,
  `Price` DECIMAL(19,2) NOT NULL,
  `Currency` VARCHAR(3) NULL DEFAULT 'USD',
  `SKU` VARCHAR(50) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  INDEX `MPMarketerKeyId_idx` (`MarketerId` ASC),
  INDEX `MPProductKeyId_idx` (`ProductId` ASC),
  CONSTRAINT `MPMarketerKeyId`
    FOREIGN KEY (`MarketerId`)
    REFERENCES `offerprocessing`.`Marketers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MPProductKeyId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `offerprocessing`.`Products` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`offerstatustypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`offerstatustypes` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`offerstatustypes` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`ConsumerOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`ConsumerOffers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`ConsumerOffers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConsumerId` BIGINT(20) NOT NULL,
  `OfferStatusId` INT(11) NOT NULL,
  `MarketerProductId` BIGINT(20) NOT NULL,
  `OfferredDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Quantity` BIGINT(20) NOT NULL,
  `MaxPrice` DECIMAL(19,2) NOT NULL,
  `EndDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IsCurrent` BIT(1) NOT NULL,
  `CreatedTiime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `OfferBundleId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `ConsumerKeyId_idx` (`ConsumerId` ASC),
  INDEX `COOfferStatusKeyId_idx` (`OfferStatusId` ASC),
  INDEX `COMPKeyId_idx` (`MarketerProductId` ASC),
  CONSTRAINT `COConsumerKeyId`
    FOREIGN KEY (`ConsumerId`)
    REFERENCES `offerprocessing`.`Consumers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMPKeyId`
    FOREIGN KEY (`MarketerProductId`)
    REFERENCES `offerprocessing`.`MarketerProducts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COOfferStatusKeyId`
    FOREIGN KEY (`OfferStatusId`)
    REFERENCES `offerprocessing`.`offerstatustypes` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`ConsumerOfferBundles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`ConsumerOfferBundles` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`ConsumerOfferBundles` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConsumerOfferId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `COBCOKeyId_idx` (`ConsumerOfferId` ASC),
  CONSTRAINT `COBCOKeyId`
    FOREIGN KEY (`ConsumerOfferId`)
    REFERENCES `offerprocessing`.`ConsumerOffers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`Suppliers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`Suppliers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Domain` VARCHAR(50) NOT NULL,
  `SuplierType` VARCHAR(50) NULL DEFAULT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `Priority` INT(11) NOT NULL,
  `Currency` VARCHAR(3) NOT NULL DEFAULT 'USD',
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`)
  )
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `offerprocessing`.`MarketerPreferredSuppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`MarketerPreferredSuppliers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`MarketerPreferredSuppliers` (
  `MarkterSupplierId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MarketerId` BIGINT(20) NOT NULL,
  `SupplierId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`MarkterSupplierId`),
  INDEX `MPSSupplierKeyId_idx` (`SupplierId` ASC),
  INDEX `MPSMarketerKeyId_idx` (`MarketerId` ASC),
  CONSTRAINT `MPSMarketerKeyId`
    FOREIGN KEY (`MarketerId`)
    REFERENCES `offerprocessing`.`Marketers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MPSSupplierKeyId`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `offerprocessing`.`Suppliers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`SupplierProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`SupplierProducts` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`SupplierProducts` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SupplierId` BIGINT(20) NOT NULL,
  `ProductId` BIGINT(20) NOT NULL,
  `Price` DECIMAL(19,2) NOT NULL,
  `Currency` VARCHAR(3) NULL DEFAULT 'USD',
  `SKU` VARCHAR(50) NOT NULL,
  `Priority` INT(11) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  `OfferBucketSize` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `SupplierKeyId_idx` (`SupplierId` ASC),
  INDEX `ProductKeyId_idx` (`ProductId` ASC),
  CONSTRAINT `ProductSupplierKeyId`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `offerprocessing`.`Suppliers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SProductKeyId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `offerprocessing`.`Products` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `offerprocessing`.`SupplierOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`SupplierOffers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`SupplierOffers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SupplierProductId` BIGINT(20) NOT NULL,
  `MinQuantity` INT(11) NOT NULL,
  `MaxQuantity` INT(11) NOT NULL,
  `OfferPrice` DECIMAL(19,2) NOT NULL,
  `EffectiveDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Ranking` INT(11) NULL DEFAULT NULL,
  `SupplierOfferStatusId` INT(11) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `IsActive` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`Id`),
  INDEX `OfferSupplierProductKeyId_idx` (`SupplierProductId` ASC),
  INDEX `SOfferStatusKeyId_idx` (`SupplierOfferStatusId` ASC),
  CONSTRAINT `OfferSupplierProductKeyId`
    FOREIGN KEY (`SupplierProductId`)
    REFERENCES `offerprocessing`.`SupplierProducts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SOfferStatusKeyId`
    FOREIGN KEY (`SupplierOfferStatusId`)
    REFERENCES `offerprocessing`.`offerstatustypes` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `offerprocessing`.`MatchedOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`MatchedOffers` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`MatchedOffers` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConsumerOfferId` BIGINT(20) NOT NULL,
  `SupplierOfferId` BIGINT(20) NOT NULL,
  `Quantity` BIGINT(20) NOT NULL,
  `MatchedOfferStatusId` INT(11) NOT NULL,
  `CreatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  `UpdatedTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedBy` VARCHAR(20) NULL DEFAULT 'urshopper',
  PRIMARY KEY (`Id`),
  INDEX `ConsumerOfferKeyId_idx` (`ConsumerOfferId` ASC),
  INDEX `SupplierOfferKeyId_idx` (`SupplierOfferId` ASC),
  INDEX `MatchedOfferStatusKeyId_idx` (`MatchedOfferStatusId` ASC),
  CONSTRAINT `ConsumerOfferKeyId`
    FOREIGN KEY (`ConsumerOfferId`)
    REFERENCES `offerprocessing`.`ConsumerOffers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MatchedOfferStatusKeyId`
    FOREIGN KEY (`MatchedOfferStatusId`)
    REFERENCES `offerprocessing`.`offerstatustypes` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SupplierOfferKeyId`
    FOREIGN KEY (`SupplierOfferId`)
    REFERENCES `offerprocessing`.`SupplierOffers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`ProductDomiciles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`ProductDomiciles` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`ProductDomiciles` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ProductId` BIGINT(20) NOT NULL,
  `MSRP` DECIMAL(19,2) NOT NULL,
  `Currency` VARCHAR(3) NULL DEFAULT 'USD',
  `Country` VARCHAR(3) NULL DEFAULT 'US',
  `SKU` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `ProductKeyId_idx` (`ProductId` ASC),
  CONSTRAINT `ProductKeyId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `offerprocessing`.`Products` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `offerprocessing`.`SupplierAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offerprocessing`.`SupplierAddress` ;

CREATE TABLE IF NOT EXISTS `offerprocessing`.`SupplierAddress` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SupplierId` BIGINT(20) NOT NULL,
  `AddressId` BIGINT(20) NOT NULL,
  `SupplierAddressTypeId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `AddressSupplierKeyId_idx` (`SupplierId` ASC),
  INDEX `SAddressKeyId_idx` (`AddressId` ASC),
  INDEX `SAddressTypeKeyId_idx` (`SupplierAddressTypeId` ASC),
  CONSTRAINT `AddressSupplierKeyId`
    FOREIGN KEY (`SupplierId`)
    REFERENCES `offerprocessing`.`Suppliers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SAddressKeyId`
    FOREIGN KEY (`AddressId`)
    REFERENCES `offerprocessing`.`Addresss` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SAddressTypeKeyId`
    FOREIGN KEY (`SupplierAddressTypeId`)
    REFERENCES `offerprocessing`.`AddressTypes` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COLLATE='utf8mb4_general_ci'
DEFAULT CHARACTER SET = utf8mb4
ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
